name: generate_oauth_key
label: Generate Clearpass API Key
type: rest

description: |
  This skillet demonstrates a simple REST api call to a Clearpass to generate a new API Key

labels:
  collection: Rest Skillets

variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: fqdn_or_ip

snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/oauth
    operation: post
    headers: 
      Content-Type: application/json
    payload: oauth.json
    output_type: json
    outputs:
      - name: token
        capture_object: access_token

  - name: get_auth_sources
    path: https://{{ TARGET_IP }}/api/auth-source?offset=0&limit=50&calculate_count=false
    operation: get
    headers: 
      Authorization: Bearer {{ token }}
      Accept: application/json
    payload: oauth.json
    output_type: json
    outputs:
      - name: auth_sources
        capture_list: name




        