name: generate_oauth_key
label: Aruba Clearpass
type: rest

description: |
  This skillet demonstrates a simple REST api call to a Clearpass to generate a new API Key and add a auth source

labels:
  collection: OCD DEV Skillets

variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: fqdn_or_ip
  - name: AUTH_SOURCE_NAME
    description: AD authentication source name
    default: Company AD
    type_hint: text
  - name: AUTH_IP
    description: AD authentication server
    default: 1.2.3.4
    type_hint: text


snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/oauth
    operation: post
    headers: 
      Content-Type: application/json
    payload: oauth.json
    output_type: json
    outputs:
      - name: token
        capture_object: access_token

  - name: get_auth_sources
    path: https://{{ TARGET_IP }}/api/auth-source?offset=0&limit=50&calculate_count=false
    operation: get
    headers: 
      Authorization: Bearer {{ token }}
      Accept: application/json
    output_type: json
    outputs:
      - name: all_auth_sources
        capture_object: _embedded.items..href


  - name: push_auth_source
    path: https://{{ TARGET_IP }}/api/auth-source
    operation: post
    headers: 
      Authorization: Bearer {{ token }}
      Accept: application/json
      Content-Type: application/json
    payload: auth-source.json
    output_type: json
    outputs:
      - name: auth_source_name
        capture_object: name




        